version: '2.1'

services:
  wait-for-startup:
    command: /bin/echo Fees Register Started
    image: alpine
    depends_on:
      fees-api:
        condition: service_healthy

  fees-api:
    image: docker.artifactory.reform.hmcts.net/fees-register/fees-api:${FEES_API_DOCKER_VERSION:-latest}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fees-database:5432/fees_register
      - SPRING_DATASOURCE_USERNAME=fees_register
      - SPRING_DATASOURCE_PASSWORD=fees_register
      - AUTH_IDAM_CLIENT_BASEURL=http://idam-api:8080
      - ROOT_APPENDER=JSON_CONSOLE
    ports:
      - 4411:8080
    links:
      - idam-api
      - fees-database
    depends_on:
      - idam-api
      - fees-database

  fees-database:
    image: docker.artifactory.reform.hmcts.net/fees-register/fees-database:${FEES_DATABASE_DOCKER_VERSION:-latest}
    environment:
      - FEES_REGISTER_DB_USERNAME=fees_register
      - FEES_REGISTER_DB_PASSWORD=fees_register

  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api
    command: --wait-for-database 30
    environment:
      - IDAM_SUPERUSER_EMAIL
      - SPRING_DATASOURCE_URL=jdbc:postgresql://idam-database:5432/idam
      - SPRING_PROFILES_ACTIVE=test
      - IDAM_TESTING_SUPPORT_ENABLED=true
      - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
      - http_proxy=
      - https_proxy=
      - no_proxy=
      - ROOT_APPENDER=JSON_CONSOLE
    ports:
      - 4551:8080
    links:
      - idam-database
    depends_on:
      - idam-database

  idam-database:
    image: docker.artifactory.reform.hmcts.net/auth/idam-database
